
openapi: 3.0.1
info:
  title: Sudoku Solver API
  description: API for solving 9x9 Sudoku puzzles
  version: 1.0.0
paths:
  /api/sudoku/solve:
    post:
      summary: Solve a 9x9 Sudoku puzzle
      operationId: solveSudoku
      requestBody:
        description: The initial Sudoku board with 0 for empty cells
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SudokuBoard'
      responses:
        '200':
          description: The solved Sudoku board
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SudokuBoard'
components:
  schemas:
    SudokuBoard:
      type: object
      properties:
        board:
          type: array
          items:
            type: array
            items:
              type: integer
              minimum: 0
              maximum: 9
          description: A 9x9 grid representing the Sudoku puzzle
          example: [[5,3,0,0,7,0,0,0,0],[6,0,0,1,9,5,0,0,0],[0,9,8,0,0,0,0,6,0],[8,0,0,0,6,0,0,0,3],[4,0,0,8,0,3,0,0,1],[7,0,0,0,2,0,0,0,6],[0,6,0,0,0,0,2,8,0],[0,0,0,4,1,9,0,0,5],[0,0,0,0,8,0,0,7,9]]
      required:
        - board
